// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace SpotifyListener.DatabaseManager.Models
{
	//You can get Utilities package via nuget : Install-Package Deszolate.Utilities.Lite
	//[Utilities.Attributes.SQL.Table("ListenHistory")]
	public partial class ListenHistory
	{
		public string Track { get; set; }
		public string Album { get; set; }
		public string Artist { get; set; }
		public string Genre { get; set; }
		public string Type { get; set; }
		public string Url { get; set; }
		public DateTime? PlayOn { get; set; }
		public int? ListeningSeconds { get; set; }
	}
}

